[project]
name = "r-colocboost"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[system-requirements]
libc = { family="glibc", version="2.17" }

[tasks]
devtools_document = "R -e 'devtools::document()'"
devtools_test = "R -e 'devtools::test()'"
codecov = "R -e 'covr::codecov(quiet = FALSE)'"
build = "R -e 'devtools::build()'"
rcmdcheck = "R -e 'pkg <- list.files(\"..\", pattern = \".tar.gz\", full.names = TRUE); rcmdcheck::rcmdcheck(path = pkg[1], args = c(\"--as-cran\"))'"
use_major_version = "R -e 'usethis::Use_version(which = \"major\", push = FALSE)'"
use_minor_version = "R -e 'usethis::use_version(which = \"minor\", push = FALSE)'"
use_patch_version = "R -e 'usethis::use_version(which = \"patch\", push = FALSE)'"

[feature.r43]
dependencies = {"r-base" = "4.3.*"}

[feature.r44]
dependencies = {"r-base" = "4.4.*"}

[environments]
r43 = {features = ["r43"]}
r44 = {features = ["r44"]}

[dependencies]
"r-ashr" = "*"
"r-covr" = "*"
"r-devtools" = "*"
"r-mass" = "*"
"r-rcmdcheck" = "*"
"r-tidyverse" = "*"
