name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - .github/*
      - .gitignore
      - README.md

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI (${{ matrix.platform }} / ${{ matrix.environment }})
    runs-on: ${{ matrix.runner }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest]
        environment: ["r44", "r45"]
        include:
          - runner: ubuntu-latest
            platform: linux-64
          - runner: macos-latest
            platform: osx-arm64

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create TOML from recipe
        run: |
          .github/workflows/create_toml_from_yaml.sh ${GITHUB_WORKSPACE}
          mkdir /tmp/pixi
          mv ${GITHUB_WORKSPACE}/pixi.toml /tmp/pixi

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: /tmp/pixi/pixi.toml

      - name: Run unit tests
        run: pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml devtools_test

      - name: Run R CMD CHECK
        run: |
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml build
          pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml rcmdcheck

      - name: Check unit test code coverage
        if: matrix.runner == 'ubuntu-latest' && matrix.environment == 'r44'
        run: pixi run --environment ${{ matrix.environment }} --manifest-path /tmp/pixi/pixi.toml codecov
